version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - dependencies
      - major-update
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
